bootstrap_common: &bootstrap_common
  commands: 
    - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
    - ./bootstrap.sh /opt/metwork-mfext-$${TARGET_DIR}
    - cat adm/root.mk

build_common: &build_common
  commands:
    - export METWORK_BUILD_OS=${OS_VERSION}
    - make
    - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm
    - mv /opt/metwork-mfext-$${TARGET_DIR}/*.rpm .

pipeline:

  bootstrap:
    image: metwork/mfcom-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    environment:
      - TARGET_DIR=${DRONE_BRANCH##release_}
    <<: *bootstrap_common
    when:
      event: push
      branch: [ master, release_* ]

  bootstrap_pr:
    image: metwork/mfcom-${OS_VERSION}-buildimage:master
    environment:
      - TARGET_DIR=master
    <<: *bootstrap_common
    when:
      event: pull_request
      branch: [ master ]

  build:
    image: metwork/mfcom-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    environment:
      - TARGET_DIR=${DRONE_BRANCH##release_}
    <<: *build_common
    when:
      event: push
      branch: [ master, release_* ]

  build_pr:
    image: metwork/mfcom-${OS_VERSION}-buildimage:master
    environment:
      - TARGET_DIR=master
    <<: *build_common
    when:
      event: pull_request
      branch: [ master ]

  publish:
    image: metwork/mfcom-${OS_VERSION}-buildimage:${DRONE_BRANCH}
    commands:
      - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
      - mkdir -p /private/metwork_addons/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - cp -f *.rpm /private/metwork_addons/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
      - createrepo --update /private/metwork_addons/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    volumes:
      - /private:/private
    when:
      event: push
      branch: [ master, release_* ]
    

matrix:
  OS_VERSION:
    - centos6
    - centos7

branches: [ master ]
