pipeline:
  bootstrap:
    image: metwork/mfcom-${OS_VERSION}-buildimage:integration
    commands:
      - if test "$${FORCED_OS_VERSION}" != ""; then if test "$${FORCED_OS_VERSION}" != "${OS_VERSION}"; then echo "step bypass"; exit 0; fi; fi
      - ./bootstrap.sh /opt/metwork-mfext-master
      - cat adm/root.mk
  build:
    image: metwork/mfcom-${OS_VERSION}-buildimage:integration
    commands:
      - export METWORK_BUILD_OS=${OS_VERSION}
      - make
      - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm
      - mv /opt/metwork-mfext-master/*.rpm .

matrix:
  OS_VERSION:
    - centos6
    - centos7

branches: [ master ]
